In [ ]:
import numpy as np
import torch

import torch

import torch

x = torch.tensor(
    [
        [10, 20, 30],
    ]
)

indices = torch.tensor(
    [
        [0],
    ]
)

result = torch.gather(x, dim=1, index=indices)

print(result)

tensor([[10]])


In [40]:
torch.cat([tensor_2d, tensor_2d])

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [27]:
print(torch.tensor([1]).view(1, -1))

tensor([[1]])


In [20]:
print(torch.tensor([1, 2]).unsqueeze(1))
print(torch.tensor([1, 2]).unsqueeze(1).shape)

tensor([[1],
        [2]])
torch.Size([2, 1])


In [29]:
torch.tensor(True).view(1, -1).float()

tensor([[1.]])